@startuml
skinparam classAttributeIconSize 0
abstract Command {
 - commandString
 - taskExpression
 + execute(Group)
}
Command <|-- AddCommand
Command <|-- DeleteCommand
Command <|-- EditCommand
Command <|-- FindCommand
Command <|-- ListCommand
@enduml