@startuml
left to right direction
abstract Command
Command <|-- AddCommand
Command <|-- AddMemberCommand
Command <|-- AddTransactionCommand
Command <|-- AddGroupCommand
Command <|-- DeleteCommand
Command <|-- DeleteMemberCommand
Command <|-- DeleteTransactionCommand
Command <|-- DeleteGroupCommand
Command <|-- EditCommand
Command <|-- EditMemberCommand
Command <|-- EditTransactionCommand
Command <|-- FindCommand
Command <|-- FindBorrowerCommand
Command <|-- FindDebtCommand
Command <|-- FindLenderCommand
Command <|-- FindTransactionCommand
Command <|-- ListCommand
Command <|-- ListDebtCommand
Command <|-- ListMemberCommand
Command <|-- ListTransactionCommand
Command <|-- ListGroupCommand
Command <|-- ClearCommand
Command <|-- HelpCommand
Command <|-- PINCommand
Command <|-- SettleCommand
Command <|-- ExitCommand
@enduml