@startuml
left to right direction

abstract class longah.commands.Command {
+ {abstract} execute(Group)
}

class longah.node.Transaction {
+ <<Create>> Transaction(String,MemberList)
+ <<Create>> Transaction(Member,ArrayList<Subtransaction>,MemberList)
+ <<Create>> Transaction(Member,ArrayList<Subtransaction>,MemberList,String)
+ void parseTransaction(String,MemberList)
+ void addBorrower(String,MemberList,Member)
+ Member getLender()
+ boolean isInvolved(String)
+ String toString()
+ ArrayList<Subtransaction> getSubtransactions()
}

class longah.util.TransactionList {
+ void addTransaction(Transaction)
+ void addTransaction(String,MemberList)
+ void remove(String)
+ void clear(MemberList)
+ ArrayList<Transaction> getTransactions()
+ String findLender(String)
+ String findBorrower(String)
+ String findTransactions(String)
+ void editTransactionList(String,MemberList)
+ String findDebts(String)
+ void deleteMember(String,MemberList)
}

class longah.util.MemberList {
+ <<Create>> MemberList()
+ void addMember(String)
+ boolean isMember(String)
+ Member getMember(String)
+ String listMembers()
+ void updateMembersBalance(TransactionList)
+ int getMemberListSize()
}

class longah.util.Subtransaction {
+ <<Create>> Subtransaction(Member,Member,double)
+ double getAmount()
}

class longah.handler.UI {
+ {static} void showWelcomeMessage()
+ {static} void showCommandPrompt()
+ {static} String getUserInput()
+ {static} void showMessage(String)
+ {static} void printSeparator()
}

class longah.node.Member {
+ <<Create>> Member(String)
+ void setName(String)
+ void addToBalance(double)
+ double getBalance()
+ String getName()
+ boolean isName(String)
}

class longah.handler.PINHandler {
+ <<Create>> PINHandler()
+ {static} void loadPinAndAuthenticationEnabled()
+ {static} void savePinAndAuthenticationEnabled()
+ {static} void createPin()
+ {static} void authenticate()
+ {static} String getSavedPin()
+ {static} boolean getAuthenticationStatus()
}

class longah.LongAh {
+ {static} void init()
+ {static} void main(String[])
}

class longah.node.Group {
+ <<Create>> Group(String)
+ void setGroupName(String)
+ String getGroupName()
+ void setMemberList(MemberList)
+ MemberList getMemberList()
+ void setTransactionList(TransactionList)
+ TransactionList getTransactionList()
+ void updateTransactionSolution()
+ void settleUp(String)
+ void saveMembersData()
+ void saveTransactionsData()
+ void saveAllData()
+ String listDebts()
}

class longah.handler.InputHandler {
+ {static} Command parseInput(String)
+ {static} Command parseCommand(String,String)
}

class longah.handler.StorageHandler {
+ <<Create>> StorageHandler(MemberList,TransactionList,String)
+ void loadMembersData()
+ void loadTransactionsData()
+ void saveMembersData()
+ void saveTransactionsData()
}

longah.commands.Command --> longah.util.MemberList
longah.commands.Command --> longah.node.Transaction
longah.commands.Command --> longah.handler.UI
longah.commands.Command --> longah.util.MemberList
longah.commands.Command --> longah.util.MemberList
longah.commands.Command --> longah.util.TransactionList
longah.commands.Command --> longah.util.TransactionList
longah.commands.Command --> longah.util.TransactionList
longah.commands.Command --> longah.util.TransactionList
longah.commands.Command --> longah.handler.PINHandler
longah.commands.Command --> longah.node.Group
longah.commands.Command --> longah.util.TransactionList
longah.commands.Command --> longah.util.MemberList
longah.handler.InputHandler --> longah.commands.Command
longah.handler.StorageHandler --> longah.util.MemberList
longah.handler.StorageHandler --> longah.util.TransactionList
longah.node.Group --> longah.util.MemberList
longah.node.Group --> longah.util.TransactionList
longah.node.Member --> longah.util.MemberList
longah.node.Transaction --> longah.util.MemberList
longah.node.Transaction --> longah.util.Subtransaction
longah.util.MemberList --> longah.node.Member
longah.util.MemberList --> longah.util.TransactionList
longah.util.Subtransaction --> longah.node.Member
longah.util.Subtransaction --> longah.node.Member
longah.util.TransactionList --> longah.node.Transaction
longah.util.TransactionList --> longah.util.MemberList



@enduml
